dillonkearns/elm-graphql

.travis.yml, README.md
We also include a workaround for making tests run much quicker on CI
systems. Finally there were uncommitted changes to the Star Wars
example.
=> Setup Travis for running tests

src/Graphqelm/Generator/Normalize.elm, tests/Generator/NormalizeTests.elm
Here is an update the normalizes all the Elm keywords, as listed in the Elm compilers Parser code.
I updated the unit tests to test all keywords, but I am not sure if I like this style, where the test and the code basically share the same data, and therefor testing the whole list bring little extra value over testing a single entry.
=> Normalize all Elm keywords

README.md
[RawGit](https://rawgit.com/) is shutting down. This PR replaces the RawGit link with the recommended alternative - [jsDelivr](https://www.jsdelivr.com/). jsDelivr is a free and fast open source CDN hosting all files from GitHub and npm.
I have tested this at https://github.com/martimatix/logo-graphqelm and confirm that it renders correctly in a Github readme.
=> Replace RawGit with jsDelivr

src/Graphql/Http.elm
In order to do something with the errors in HttpError the app needs to pattern match on that type.
This type is not exported atm.
Expose `HttpError`
=> Expose HttpError

src/Graphql/Document/Field.elm, tests/DocumentTests.elm
This fixes issue #120 by selectively modifying the alias function to not alias `__typename`. There may be a better way to tackle the issue, but this works in my case as is.
=> Don't alias __typename

CHANGELOG-ELM-PACKAGE.md, CHANGELOG-NPM-PACKAGE.md
Despite looking at these changelogs for the entire year thus far, I failed to notice until just now that they failed to roll over the year in January. Caused minor confusion for a few seconds. 😃
=> Correct years in changelog dates

README.md
Added recently by the Hasura team https://github.com/hasura/graphql-engine/pull/2427
It's very detailed and includes everything from querying, deleting, mutating and even subscriptions.
=> Add reference to Hasura elm-graphql course

src/Graphql/Http.elm
=> Switch discardParsedErrorData from returning a () to an unconstrained a

generator/src/elm-graphql.ts
Hello @dillonkearns, I'm not very proud of this fix but it is a quick workaround in order to remove the annoying warning message :)
=> Remove elm production warning

src/Graphql/Document/Field.elm
No reason to generate `index` when it's not being used. `indexedMap` traverses the list twice: once to compute the indeces and once to do the actual mapping.
=> Small performance improvement

generator/src/Graphql/Generator/Normalize.elm, generator/tests/Generator/NormalizeTests.elm
Normalize field names that are only `_`'s to valid Elm identifiers instead of stalling the CLI.
`_` is valid for assignments in Elm, but not for reading values. You can't read from `_`, they're just thrown away. So this is the normalization strategy now with this PR:
* `_` => `underscore_`
* `__` => `underscore__`
Fixes #285.
=> Handle normalization for field names that are only underscores.

README.md
There might be better fixes here — `QueryHuman` and `Human`, perhaps.
=> fix type collision in readme's first code sample

src/Graphql/SelectionSet.elm
I'm starting to go through the docs, so I'm making small PRs when I notice typos :slightly_smiling_face:
=> Fix typo in docs

generator/src/Graphql/Generator/Enum.elm
I don't know how to do this ( / run them), but the end-to-end tests and the examples should be updated, as I saw this typo a lot in there.
Let me know how I can do that if you wish for me to do that.
Have a good day :)
=> Fix typo in generated documentation

src/Graphql/Operation.elm
Replace with subscription-specific information.
=> Remove reference to mutation in documentation of `RootSubscription`.

elm.json, ete_tests/elm.json, examples/complex/elm.json, examples/elm.json, examples/subscription/elm.json, src/Graphql/Document/Field.elm, src/Graphql/Document/Hash.elm
Hi, there is a problem with a compilation of this library due to a missing dependency, as stated in [the Murmur3 repo](https://github.com/robinheghan/murmur3/issues/5).
Since we don't know if the repo is actively maintained, copying the Murmur3 module inside `elm-graphql` seems a good compromise. I would also evaluate alternatives like hashing libraries with smaller footprint
=> Integrate Murmur3 module

docs/Subscriptions-FAQ.md
The link to the subscriptions example in the subscriptions FAQ is currently broken, this PR aims to fix it!
=> Fix reference to subscriptions example in the subscriptions docs

package-lock.json, package.json
To resolve the vulnerability mentioned in #399, it suffices to upgrade graphql-request to the latest version.
To be sure it did not break anything, I tried these public graphql sites, both with the original version and the updated version, then `diff`-ed the results and there were none. So I am pretty sure this should cause no issues.
```
https://pristine-gadget-267405.appspot.com/graphql/
https://api.graphql.jobs/
http://api.catalysis-hub.org/graphql
https://countries.trevorblades.com
https://bahnql.herokuapp.com/graphql
https://api.digitransit.fi/routing/v1/routers/finland/index/graphql
https://portal.ehri-project.eu/api/graphql
```
=> Update graphql-request to v3.3.0

src/Graphql/SelectionSet.elm
I noticed this link on the docs goes to the old repo (which also has outdated references to `Graphql.Field`, [which have already been fixed](https://github.com/dillonkearns/elm-graphql/commit/e4bbe99065727526fea045cb678e1167694105d4) in this repo).
Here's the section with the link:
https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-SelectionSet#result-orfail-transformations
=> Fix link (to dillonkearns/elm-graphql)

examples/src/Github/Object/User.elm, generator/src/formatted-write.ts, package-lock.json, package.json
Fixes #442.
This change removes `elm-format` as a peer-dependency.
For reference, here are some other projects that have explored different approaches to this problem:
https://github.com/rtfeldman/node-test-runner/issues/419
This is how `elm-review` currently runs `elm-format` and gives errors if it isn't found: https://github.com/jfmengels/node-elm-review/blob/6d0cf84ac554bf95bd21ecfac251e7a466ad2016/lib/autofix.js#L116-L170. It first tries to find it on the PATH, and then tries to run it with `npx`. But from conversations with @lydell, this is probably unnecessary, just checking on the PATH should be sufficient.
=> Don't require npx when running elm-format. Remove as peer-depdency.

CHANGELOG-NPM-PACKAGE.md, generator/src/cli/generated-code-handler.ts, generator/src/elm-graphql.ts, package-lock.json, package.json
With Node >= 10.12.0, `fs-extra` can be replaced with built-in `fs` functions.
=> Remove fs-extra and use built-in fs package.

generator/src/Graphql/Generator/InputObjectLoops.elm, generator/tests/Generator/InputObjectLoopsTests.elm
When generating input object types with elm-graphql, some input objects get incorrectly flagged as containing loops, and get wrapped in a custom type.
Reference issue: https://github.com/dillonkearns/elm-graphql/issues/33
Create an input object type that contains at least 3 layers of other input objects.
Example (in graphql schema notation):
```graphql
input TypeOne {
typeTwo: TypeTwo!
}
input TypeTwo {
typeThree: TypeThree!
}
input TypeThree {
typeFour: TypeFour!
}
input TypeFour {
name: String!
}
```
Generate this schema using elm-graphql. `TypeOne` will be generated as:
```elm
type alias TypeOneRaw =
{ typeTwo = TypeTwo }
type TypeOne
= TypeOne TypeOneRaw
```
The bug originates when we descend down the type trees to inspect the fields of the first input object that are input objects …
=> Fix a minor bug in circular reference detection of deeply nested input objects

src/Graphql/Document/Field.elm, tests/DocumentTests.elm
Fields will have collisions if there is more than one with the same field name or field alias. This ensures that composite fields with the same field name or field alias are merged into one composite.
Fixes #495.
=> Merge composite children

elm.json, ete_tests/elm.json, examples/complex/elm.json, examples/elm.json, examples/subscription/elm.json, src/Graphql/Document/Field.elm, tests/DocumentTests.elm
Hi!
I run into a problem when sending multiple mutations in a single request to Hasura server backed with PostgreSQL. The mutation query requires to execute `update` and `insert` operations sequentially in a transaction of PostgreSQL, however `elm-graphql` is serializing their GraphQL operations into alphabetical order which is the problem.
More specifically, with this code we expect the `updateUser` runs first then the `insertUser`.
```
SelectionSet.map2 Tuple.pair updateUser insertUser
```
However actually this is serialized to something like follows.
```
query: “mutation {
insert_user12345: insert_user(…)
update_user12345: update_user(…)
}”
```
With this query, Hasura issues PostgreSQL query in order of `insert` then `update` which will fail in my schema. I think this behavior is …
=> Preserve the serialization order for mutations

generator/elm.json, generator/src/Main.elm
Display validation message with an additional "I expected this to be" so the output becomes:
```
Validation errors:
Invalid `--scalar-codecs` option.
I expected this to be matching "^[A-Z][A-Za-z_]*(\.[A-Z][A-Za-z_]*)*$", but got 'src/CustomScalarCodecs'
```
=> Use Cli.Validate.regexWithMessage when validating module name

generator/src/Main.elm
At Crowdstrike we have a build setup that uses Bazel. Much like in `Make` build target take input files and produce output files. If an input file changes, the the target must be rebuilt.
In order for elm-graphql to generate files - when there is are custom scalar codecs - it will validate the custom scalar codec Elm file to see if the definitions match the scalar types in the GQL schema.
This becomes a problem because since the custom Elm file can import other parts of the codebase. Effectively the entire Elm codebase becomes a dependency for the "GQL API client generation" build step. So, if any Elm file is changed, the client must be regenerated! This in our case adds ca. 8s to each build iteration, which is not cool in a dev environment.
This PR adds CLI flag `--skip-validation` which …
=> Allow skipping validation of custom scalar codecs.

README.md, generator/src/Graphql/Generator/Decoder.elm, src/Graphql/Http/GraphqlError.elm, src/Graphql/OptionalArgument.elm
It looks like the content on facebook.github.io was split over several
domains at some point, with the `/graphql` namespace moving over to
spec.graphql.org, and the `/relay` namespace moving to relay.dev.
This PR updates all references to facebook.github.io to the proper
documentation domain.
=> Update (and fix) the domain for graphql specification links

generator/src/elm-graphql.ts
I believe this should be `codecs`
=> Change `decoders` to `codecs` in error message

src/Graphql/Document/Field.elm, tests/DocumentTests.elm
I believe #595 introduced a regression of #95. I believe this pull request resolves it.
=> Hash sibling fields with the same field name but clashing types.

src/Graphql/Http.elm
The documentation says `request` when it means `send`.
=> Small documentation fix.

src/Graphql/SelectionSet.elm
There was a parenthesis missing, so the code was not properly formatted.
This does move the note in the imports, but I'd say this is okay.
=> Fix example for SelectionSet.mapOrFail
